### ISSUE TITLE
2nd deployment with cache folder skips some resources

### ISSUE THREAD

**Issue by Notexe** [hitman-resources/simple-mod-framework#138]
Here is a table of the resources that got packed into the game on the 1st deployment (Without the cache folder present) and the resources that got missed on the 2nd deployment (WIth the cache folder present).

This was done using the Ibis mod with only Eagle enabled (Which I believe you have access to)

**chunk0patch300:**
Resource | 1st Deployment | 2nd Deployment
-- | -- | --
0009BDD52F9A8294.TEMP | Yes | No
00234D0CFE97C1B4.GFXI | Yes | No
003C341C1B871753.GFXI | Yes | No
006E96FD675AEEC3.TBLU | Yes | No
007A1ED19E069268.GFXI | Yes | No
008AA770BE9174AD.GFXI | Yes | No
00AAAFF018B083A1.GFXI | Yes | No

**chunk22patch300:**
Resource | 1st Deployment | 2nd Deployment
-- | -- | --
0005E6A90297DFAE.TEMP | Yes | No
005EDB3E7D39ADD7.TBLU | Yes | No

**Comment by hitman-resources** [comment]
Fixed in 01756fd.
